React capstone project - Metrics webapp
Ibtisam34/Metrics-webapp pull request #2
Opened 2023-01-19 07:37 UTC by Ibtisam34

- [ ]  This React capstone project is about building a mobile web application to check a list of metrics (numeric values) that I had created making use of React and Redux.

I selected an API that provides numeric data about a topic that I liked and then build we web around it. The web appill has several pages:

1. one page with a list of items that could be filtered by some parameters.

2. one page for the item details.

2023-01-19 11:57 UTC, fobadara requested changes
Hi @Ibtisam34, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are passing
✅ Good first attempt

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 11:57 UTC, fobadara commented on README.md
> +[live presentation](https://www.loom.com/share/fddfc6960af443308443f38ba92144b6)
[OPTIONAL] Kindly give your live presentation a heading and put it on a separate line. I almost made the absence of a video link a required change

2023-01-19 11:57 UTC, fobadara commented on README.md
> +[live presentation](https://www.loom.com/share/fddfc6960af443308443f38ba92144b6)
[REQUIRED] Kindly reduce the video to 5 minutes. The requirements are to present your project, make it a maximum of  5 minutes and show us a piece of code you are proud of. There was no need to show us the bulk of your code

2023-01-19 11:57 UTC, fobadara commented on README.md
> +👥 Authors
[OPTIONAL] Kindly make. `authors` singular

2023-01-19 11:57 UTC, fobadara commented on README.md
> +
[REQUIRED] Kindly give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/). You need to include the links also

2023-01-19 11:57 UTC, fobadara commented on README.md
> +NOTE: we recommend using the MIT license - you can set it up quickly by using templates available on GitHub. You can also use any other license if you wish.
[OPTIONAL] Some of. your subheadings are squeezed together like authors, future features, contribution, show your support, license and faq. Make them bold also for example:
```
## Faq
```
The two `#` and a space will make it a subheading or a single `#` for a main heading

2023-01-19 11:57 UTC, fobadara commented on src/pages/homepage/weathercountries.js
> +  );
[REQUIRED] One of the aims of this project is to teach you to follow client requirements. Kindly ensure your app design is close to Nelson's template in terms. of typography and layout
![image](https://user-images.githubusercontent.com/62938735/213434348-b32edf3f-e7ec-4ebe-b9ee-67c6ce44e13c.png)



[OPTIONAL] I think adding pagination and a search bar to your app will make it more user friendly

2023-01-19 11:57 UTC, fobadara commented on src/pages/weatherstate/weatherstates.js
> +      </div>
[REQUIRED] One of the aims of this project is to teach you to follow client requirements. Kindly ensure your app design is close to Nelson's template in terms. of typography and layout

![image](https://user-images.githubusercontent.com/62938735/213435276-59d08227-4ffb-4ac0-b67f-57f1f756f539.png)

2023-01-19 12:49 UTC, Ibtisam34 commented on src/pages/homepage/weathercountries.js
> +  );
https://github.com/fobadara sir here Iam not getting could you plz join huddle to tell me further

2023-01-20 10:39 UTC, fobadara requested changes
Hi @Ibtisam34, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some haven't been addressed yet.


 ## Highlights
✅ Linters are passing

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 10:39 UTC, fobadara commented on src/pages/homepage/weathercountries.js
> +  );
[REQUIRED] Some of your texts are going out of its box

2023-01-20 10:39 UTC, fobadara commented on src/pages/homepage/weathercountries.js
> +            name={country.name}
[REQUIRED] Try to focus more on the mobile screen size Kindly make sure that you have two columns for items without space at the top, bottom, left or right just like the design. The boxes should be touching each other

![image](https://user-images.githubusercontent.com/62938735/213675315-3b2d4da6-c067-4716-9740-eb48e0af31a6.png)

2023-01-20 13:30 UTC, levy002 approved these changes
### Hello @Ibtisam34 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 13:50 UTC, merged